booqable/chameleon-theme

assets/account.css, assets/base.css, assets/carousel.css, assets/carousel.js, assets/collections.css, assets/images.css, config/settings_data.json, config/settings_schema.json, sections/images.liquid, snippets/root-styles.liquid
At the moment there are 2 overlay colors in Tough theme: black and white. These colors were set up via static CSS variables and the Romantic theme has a different black color, so the customers should have the possibility to edit these 2 colors
What should be done:
- Add 2 extra color pickers to each color set to settings_schema.json
- Make sure that navigation buttons/dots are visible on top of the overlay background when the overlay background is different on other slides
Changelog: 
1. Added some logic to the carousel.js file
2. Added 2 extra color pickers to each color set to theme settings
3. Slightly changed the logic of full-width carousel in the Hero section on Homepage
4. Added styles to sections that have images with overlays
5. Claned up CSS variables 
Before: 
After:
=> Added "Alternative background" and "Alternative color" to theme settings

sections/products.liquid
Now that the carousel layout is optional, we should rename the section and its description.
Changelog:
1. Changed section name
2. Changed section description
=> Rename "Products carousel" section to "Products"

sections/footer.liquid
Added link "Powered by Booqable" in the footer. Appearance is controlled by `show_powered_by` global attribute:
Requires: https://github.com/saladdays-nl/booqable/pull/9071
=> Control "Powered by Booqable" with `show_powered_by` global attribute

assets/carousel.css, assets/carousel.js, assets/header.js, assets/images.js, assets/main.js, assets/maps.js, assets/tabs.js, assets/touch-device-notch.js, layout/theme.liquid, sections/images.liquid
New issues regarding the Images section with video playback:
1. There are errors in the console if more than one `Images` section is added per page
2. When try playing the videos in both sections, the first works, but the second doesn't
Changelog:
1. Scripts that are used with videos moved to theme.liquid
2. Added section `id` to elements that are used by Youtube video API
Before:
After:
=> Video doesn't play in the second "Images" section

assets/base.css, config/settings_schema.json, layout/theme.liquid, sections/hero-product.liquid, sections/hero-search.liquid, sections/hero.liquid, sections/images.liquid, snippets/date-picker.liquid, snippets/variables-cart-lines.liquid, snippets/variables-cart-services.liquid, snippets/variables-cart-totals.liquid, snippets/variables-mini-cart.liquid, snippets/variables-product-gallery.liquid, snippets/variables-product-quantity.liquid, snippets/variables-product-variations.liquid
Added `date-picker-modal ` component to the layout. It was done to resolve the issue if `Add to cart` button behavior is set to `Checkout`, so the mini cart is not shown on the page, and the `Date picker` section is also not added to the page, but during cart overdue evaluation if the dates are in past there is no picker mounted, so the dates can't be changed.
Besides that, during testing `date-picker-modal `'s colors was noticed the issue that the default (fallback) colors of all shop components didn't work at all
=> Added date picker modal to layout, added default colors

assets/collections.css, assets/rx.css, snippets/root-styles.liquid
The first purpose of the PR is to make the collection images visible and have the same height in the `Collections` section in Safari.
The second one the fonts didn't work properly if the font name consists of 2 words with space between them then always the fallback font rendered
And added/corrected some styles of `wysiwyg` editor.
=> Collection images are not loaded in Safari

assets/logos.css
There was an extra `padding-left` and Logos were not centered perfectly if the title is in `center` mode on the desktop
=> Removed unneeded styles of Logos

assets/collections.css
There was an issue that selecting `dark` overlay made the background and text on top of it dark as well, so this text wasn't readable.
Also, the overlay was solid, not a gradient if the collection is not chosen.
=> Collection overlay color improvements

assets/header.js
The `menuOverflow` function is bound to a click event listener on the whole body.
It uses line #183 to short-circuit clicks on elements that are not intended targets.
However, when menu is not rendered (can be configured in settings), the `menuOpener` is null. If element that was clicked does not have `previousElementSibling` then `target` will also be null. This will cause `target !== this.menuOpener` to be false, the short-circuit will not be triggered and `this.addOverflow()` will be called.
This applies `overflow-hidden` CSS class to the body, which prevents web page from scrolling, making it seem like the website is frozen.
To fix this issue, we make sure that if `target` is undefined we immediately short-circuit this function.
=> Fix freezing website when main menu is not present

assets/carousel.css, assets/date-picker.css, assets/images.css, assets/rx.css, sections/date-picker.liquid, snippets/date-picker.liquid
Although the date picker is an option for certain sections, it should also be available as a separate section for every page. At this time, the option to add the date picker is missing from the "Add section" list.
Changelog:
1. Added separate `Date picker` section
2. Carousel dots of `Images` section were centered
3. Fixed `line-height` of the `title` of `Images` section
Seems like the date picker works without any errors even if there is more than 1 copy on the page
=> Added separate date picker section

snippets/product-card.liquid
We allow HTML in product descriptions, this caused an issue when truncating them.
Example:
`<b>This is a very long description that is bold</b>`
Would be truncated to
`<b>This is a very long...`
Which would leave us with an unclosed tag that would break the layout.
As a solution we make sure to strip HTML tags before truncating.
**Before**
**After**
=> Strip HTML before truncating to avoid not-closed tags

config/settings_data.json
The "current" key was removed, however it was used as a fallback for "construct" theme as it was missing it's own key. Here we are reusing "default" as "construct".
=> Fix Construct theme key

config/settings_data.json
In the current version of Focus, the Element style is set to Classic on install. It should be set to Modern.
=> Focus theme's Element style should be Modern by default

config/settings_data.json, sections/footer.liquid, snippets/payments.liquid
There is an issue that the SVG icons of the payment methods in the footer are really big.
So there was added some styles to make them the same size
Before:
After:
=> Fix big payments icons

snippets/image.liquid
The media queries were incorrect and were always loading the smallest size of the image which would cause blurry images. Note that the first matching media query in the `srcset` is used, and the rest are ignored. First `min-width` would be matched (as for example 2000px viewport width is larger than 450px defined in query) and smallest image used.
Logic for choosing image size is changed. Now the image size defines the expected size relative to the viewport and media queries take care of loading the right image size.
For example:
A hero image would be approximately as wide as the whole viewport, so we would use the xxl size.
A testimonial image would be approximately as wide as half of the viewport (as it is show on the side), so we would use the l size.
**Before**
**After**
=> Fix responsive images

sections/hero.liquid, sections/product-page.liquid
If in the product description add some additional elements, for example, an unordered list, it looks like the styles are not applied for the product description on the Product page
Before:
After:
=> Added styles applied within the product description

snippets/variables-cart-lines.liquid, snippets/variables-cart-services.liquid
After Herman's review of the Cart Next component, there are few issues, rather color inconsistents in the Chameleon theme. So there were added and changed CSS variables of the Services block and the color of "Your cart is empty" text according to the selected color palette
=> Fixed styles of Cart next

assets/maps.js
The issue was that the class responsible for initializing the maps for "Locations" section was called `Map` which was basically overwriting the native JavaScript class and the original was used in the reCaptcha. This PR resolves the issue by renaming the class from `Map` to `LocationMap`
=> Fix: "Locations" and "Contact Form" incompatibility

assets/hero.css, sections/hero-product.liquid, sections/hero-search.liquid, sections/hero.liquid, sections/images.liquid, sections/split-screen.liquid, snippets/date-picker.liquid
Since more and more sections are using the `Date picker`, there were changes to its snippet recently. And the `global` store settings didn't transmit to the snippet. So the purpose is to pass `global settings` from all sections that use the Date picker to its snippet.
Also, the Hero section's code was cleaned up on the Product page.
=> Fixed bug of default colors of the date picker colors is showing always

sections/locations.liquid, sections/split-screen.liquid
We are going to hide two sections from the theme editor.
**Locations** - these were accidentally released early and still need some refinement.
**Split screen** - this was just developed but there was an oversight on product level as a very similar section still exists. There are concerns that this will confuse customers and add more code to maintain in the future. We will leave it in the code base for now but make it unavailable to customers.
=> Hide Locations and Split screen sections in the editor

assets/images.css
Added `min-height` instead of `height` CSS property on slide height for `Images` section on the desktop
Before: 
After:
=> Image slider controls overlap the CTA buttons

sections/hero.liquid, templates/collection.json
Previously title of hero section would default to `page_title` on all pages. This looks good on most pages, but on collection pages it would render as "Collection name | Store name" which is not ideal.
With this change, default hero title will be collection title only.
=> Use collection title as default hero title

sections/date-picker.liquid
The customer reported the issue, she is using the Construct theme, but the problem is that when she uses a date picker section, the date picker doesn't take the selected colors. It remains with the default theme color
Only the date picker included in the "images" section takes the correct color.
With a more detailed study of the problem revealed that the store settings were not passed to the date picker snippet
=> Fixed issue when Date picker section doesn't take the selected colors

sections/images.liquid
The main purpose of this PR is to fix the issue reported by the customer when the `image mobile` was not rendered at all in the `Images` section.
Before:
After:
=> Fixed an issue where the "mobile image" was not displayed.

sections/images.liquid
We have a rich text editor for the description of the image field, but we are stripping HTML so styling is not displayed. This PR removes HTML stripping.
Additionally truncation is also removed as it can break HTML tags and cause issues in the layout.
Example:
`<p>Some long text</p>` can get truncated to `<p>Some long` which introduces an unclosed tag and breaks the layout.
=> Allow HTML in the description of the image section

sections/login-form.liquid
This PR shows/hides the create account button and guest checkout link on the login form, depending on the user settings.
=> Toggle login buttons visibility according to settings

assets/product-card.css
The issue is in `Product card` flexbox properties. Firefox browser doesn't want to work with `display: flex `and the `Product card` images aren't displayed all over the sections that use products.
So the solution is to change `display: flex` property to `display: grid`
Before:
After:
Firefox
Chrome
Safari
=> Images not loaded in the 'all collection' on firefox

assets/images.css, sections/images.liquid
The main purpose of this PR is to fix a bug reported by the Product team if the padding-bottom option has the value `none` the carousel height is flattened and the second purpose is to fix the issue of `text positioning` inside the slide
=> Fixed indents if `none` option is chosen

assets/call-to-action.css, assets/hero.css, assets/product-page.css, sections/call-to-action.liquid, sections/hero-search.liquid, sections/hero.liquid, sections/product-page.liquid, templates/cart.json, templates/collection.json, templates/construct/list-collections.json, templates/list-collections.json, templates/page.json, templates/romance/list-collections.json, templates/search.json, templates/vogue/list-collections.json
The background image is pretty much useless because of the non-adjustable overlay.
So it should have a setting of opacity percentage as we have in other sections e.g. `Images`.
Before:
After:
=> Allowing setting opacity for overlay in Hero and CTA sections

sections/login-form.liquid, sections/register-form.liquid
Flash messages contain important information that you should read before trying to log in, so we're moving them above the form.
=> Move flash messages above the forms

assets/product-card.css, sections/product-page.liquid, snippets/product-card.liquid
The purpose of the PR is to hide price separator when the prices are hidden from the store
Before:
After:
=> Hide price separator

assets/account.css, sections/register-form.liquid
The PR purpose is to introduce Terms & Agreement modal window
Clicked on the "Terms and agreements" link when creating a new customer account led you to a generic Booqable terms page. But should be the actual content of the terms and agreement that company provided. 
So in this PR implemented a modal that shows this content, instead of linking to the generic one.
=> `Terms & Agreement` modal window

sections/header.liquid, snippets/image.liquid
Make sure that we do not convert format of logo image. This enables customer to use `png` images which are sharper than the `webp` to which we convert by default.
Related [PR](https://github.com/saladdays-nl/booqable/pull/10073)
=> Keep type for logo image

layout/checkout.liquid
Previously we forgot to add the metadata to the checkout. This PR makes sure:
- Favicon is included
- Shop name is used as the title of the page
=> Add favico and shop title to checkout page

assets/product-card.css
The PR's goal is to align vertically the `price` in product card when product's description is of various heights and option `Element design` is set to `Classic`
Before:
After:
=> Aligning price vertically

sections/footer.liquid, sections/header.liquid
Increase the size we resize logo to in order to get better rendering on high-resolution (retina screens). Previously we rendered a 200px wide logo in the width of 200px, now that is increased to 400px wide image within 200px space, which looks better.
The difference is hard to notice but customers are complaining.
**Before**
**After**
=> Improve logo quality on high resolution screens

assets/main.js
This PR removes the scroll-in/out message handler from a theme to comply with the changes introduced in https://github.com/saladdays-nl/booqable/pull/10151
=> Improvement: Remove scroll messages handler and listener

assets/header.js, config/settings_data.json
The customer reported that on the Topbar section in the theme builder, the option to add WhatsApp chat through a URL (wa.me/34611111111) doesn't work. It will only offer the option to call.
However, when this link is anywhere else embedded in a button, it does work.
So the PR's goal is to remove the feature that automatically finds and adds prefixes `mailto:` and `tel:` to email addresses and phone numbers accordingly from the Topbar section
=> Removed auto-adding prefixes to emails and phone numbers

assets/carousel.css, assets/products.css, sections/products.liquid
Currently, the Product section has 2 different layouts for mobile and desktop if the `Show products as carousel` option is not chosen
So the purpose of this PR is to use only 1 layout for both desktop and mobile
Before:
After:
=> Disable carousel on mobile if `Show products as carousel` option is not chosen

templates/around/index.json, templates/chic/index.json, templates/construct/index.json, templates/construct/product.json, templates/product.json, templates/radical/index.json, templates/romance/index.json, templates/utility/index.json, templates/vogue/index.json
If clicking `See all` button next to the `Products` title while in the theme editor on a fresh theme installation there will be the preview that loads Booqable's interface
So this PR's goal is to replace all broken URLs of `See all` buttons across all templates
=> `See all` button URL correction

sections/call-to-action.liquid, sections/hero-search.liquid, sections/hero.liquid, sections/images.liquid, sections/locations.liquid, sections/mosaic.liquid, sections/numbered-blocks.liquid, sections/split-screen.liquid, sections/testimonials.liquid, sections/text-with-image.liquid
The issue we discussed on standups when the `Image resizer` is logging too many errors. Zoran said [this](https://github.com/booqable/tough-theme/pull/186) fix cut errors in half. So Zoran and I discussed this issue and decided that consequently, we could eliminate some more errors by checking the image URL in all conditions in all liquid files before rendering the image
So the PR's purpose is to add the `.url` key into every scenario involving image rendering where it is currently missing
=> Fix image URL check in liquid templates

assets/header.css, sections/footer.liquid, sections/header.liquid, snippets/image.liquid
I observed a discrepancy regarding the logo's dimensions on mobile devices, specifically within the Header and Footer. 
Delving deeper into the matter revealed that the `custom_size` attribute was missing when rendering the logo image snippet. It appears that Filip, in a recent update had been tried to increase the logo quality (visible in this [PR](https://github.com/booqable/tough-theme/pull/193)), removed this attribute, leaving only the `custom_width`. 
However, these attributes are designed to function collaboratively. 
As a result of this alteration, both `custom width` and `custom size` settings were disregarded, leading to the application of the default size `m`. 
In comparison, this size selection seems adequate for desktop displays but if taken into account mobile devices have a …
=> Update logo size for mobile

templates/activate-account.json, templates/construct/activate-account.json, templates/construct/edit-password.json, templates/construct/login.json, templates/construct/register.json, templates/construct/reset-password.json, templates/edit-password.json, templates/login.json, templates/register.json, templates/reset-password.json, templates/romance/activate-account.json, templates/romance/edit-password.json, templates/romance/login.json, templates/romance/register.json, templates/romance/reset-password.json, templates/vogue/activate-account.json, templates/vogue/edit-password.json, templates/vogue/login.json, templates/vogue/register.json, templates/vogue/reset-password.json
When accounts are disabled, account related templates throw errors in the theme editor. This PR makes sure those templates are hidden depending on the account settings.
=> Hide session pages if accounts are disabled

assets/carousel.css
Upon observation, I discovered that slides are capable of expanding to occupy all available space when their number is fewer than four. This flexibility, however, introduces the potential for the slides to adopt widths that are not proportional.
So this PR adds a limit to the slide width, which will allow all slides to have the same width regardless of the number of slides.
Before:
After:
=> Fix for the carousel slides if there are less than 4

assets/carousel.css, assets/product-card.css, assets/products.css, sections/products.liquid
Currently, we're encountering challenges concerning the visibility of carousels. Initially, when a collection including few items is selected and blocks are subsequently disabled, the entire section vanishes. Moreover, in the scenario where a collection is chosen and merely a single block is enabled, the carousel fails to function despite 'Show products as carousel' feature is active.
So the PR's goal is to fix carousel visibility issues and update some its styles
=> Fix the visibility of the Products carousel and update its styles

assets/footer.css, assets/header.css, sections/footer.liquid, sections/header.liquid, snippets/app.liquid
Similarly to https://github.com/booqable/kylie-theme/pull/116, this adds support for app blocks to the header and the footer section.
Should not get merged until support for this has landed in the main app.
=> Add support for rendering app blocks

config/settings_schema.json
The text area is breaking the JS code when there are newline characters in there.
=> Remove textarea description from Cookie Notice settings

snippets/variables-mini-cart-button.liquid
After merging this [PR](https://github.com/booqable/booqable/pull/10426) the cart icon moved up slightly, so it should be centered through the header and its new variables should be added as well
Before:
After:
=> Centering cart icon, adding new variables

assets/header.css
The mobile menu doesn't appear when the device is held vertically in Endure template. So, the logo width should be limited to display all next-to-it icons in header on narrow screens
Before:
After:
=> Limit logo width

assets/header.js
There's a problem in the Preview mode. In this mode, the search bar always shows "HTTP ERROR 404" page, even if you search for an existing product.
The problem is the URL after searching for an item.
It is redirecting to `/search?q=test` but this doesn't work with the Preview mode, it should be `/search?theme_id='here the theme id'&q'here what you're searching'`
The PR's goal is to add a lost `theme_id` parameter to URL which is required for correct search work in the Preview mode
Before:
After:
=> Fix search error in website's preview mode

assets/pagination.css, snippets/pagination.liquid
Currently, for the pagination, the `[…]` take an accent color.
It's also not very clear why the last item is a `[…]`, it should just be the number of the last page.
So, the PRs purpose is to remove accent colors for `[...]` of the pagination and make the format like `[<] [1] [2] [3] [4] […] [27] [>]`
Before:
After:
=> Refactor pagination styling and logic

assets/footer.css, assets/header.css, sections/header.liquid
The Weglot app has been using its own styles that look not good on some screen resolutions. Besides that, it doesn't use theme's variables which can take different values depending on theme settings
This PR is intended to add styles, make the app responsive, and fit into the overall design.
Before:
Header light:
Header dark:
Footer light:
Footer dark:
After:
Header:
Footer:
Testing clue: For activating the EN button, the Veglot app should be added to your Booqable account from the App store and then added as a block in the header/footer via the theme editor
=> Weglot app responsive styles

assets/mega-menu.css
The customer reported the issue with a menu with a lot of items.
When it's set up to horizontal the menu background is not applied to all the options and items go off the edges of the screen.
Before:
After:
=> Fix horizontal menu if it has a lot of items

assets/mega-menu.css, config/settings_data.json
The customer is complaining that there is an issue with the Menu with a lot of menu items in the top-level dropdown and when you choose to display the menu style vertically you can't scroll to the end of the menu
So the PR's goal is to add scroll to the top-level menu's dropdown if it doesn't have nested menus
Before:
After:
=> Not all menu items are displayed in vertical menu layout

assets/base.css, assets/top-bar.css, snippets/icon.liquid
Currently, the colors of `font-awesome` are loading with `icon.liquid` snippet file, and the colors of star icons in the Testimonials section are rendered with `font-awesome` as well but don't use the `icon` snippet, so styles are lost if they are not loaded with other sections on the page.
So the purpose of this PR is to move styles of the color of `font-awesome` icons to the `base.css` file
**Before**:
**After**:
=> Fix font awesome color issue

assets/base.css, assets/footer.css, assets/header.css
Currently, we can get a broken layout with too long words, especially it's clearly visible on narrow blocks such as in the Columns section. So in this case we have a `contentEditor` field and the customer added the email and wrapped it in the heading tag but it goes out of the block
So this PR's purpose is to add the CSS `break-word` property and avoid such issues throughout the layout
Before:
After:
=> Avoid broken layout with long words

assets/base.css, assets/images.css, assets/main.js, assets/product-card.css, sections/hero-search.liquid, sections/hero.liquid, sections/images.liquid, sections/mosaic.liquid, sections/products.liquid, snippets/product-card.liquid, snippets/root-styles.liquid
This PR's goal is to remove `strip_html` and `truncatewords` filters to save all the styling of reach text.
Also, instead of 3 dots at the end, it should add a linear gradient to the bottom of the product description on product cards dynamically, because else if the description is too small it's overlapped with the gradient and is non-visible at all.
Before:
After:
=> Remove stripping html and truncating of product excerpts

assets/product-card.css, sections/hero.liquid
This PR aims to fix the issue with pricing structure if the label of the pricing is too long
**Before:**
**After:**
=> Fix the pricing layout if a label is too long

assets/account.css, sections/accept-invitation-form.liquid, sections/login-form.liquid, sections/register-form.liquid, sections/reset-password-form.liquid, snippets/form-password-session-pages.liquid, templates/accept-invitation.json, templates/romance/accept-invitation.json, templates/vogue/accept-invitation.json
This PR goal is to implement a new `Accept invitation` page into all theme variants, and slightly refactor the code: 
remove `data-disable-with` attribute from everywhere, move form input password fields code to snippet.
Since this feature doesn't work on the production yet I can't provide screenshots (((
=> Implement `Accept invitation` page

assets/base.css, assets/header.js
The customer complains that the shopping cart doesn't look right on his website. Certainly, from his browser - Chrome. And he has to zoom out to 67% to be able to continue with the checkout.
It happens because he uses the `Sticky header` and `Menu bellow` header options and at the same time the menu has a lot of the first-level items, so the header is too tall because of that. On the other hand, the mini-cart is positioned right below the header and has hardcoded values of height and width, therefore the `Checkout` button is below the fold and never can be available for users.
Therefore, the purpose of this PR is to move the mini cart to the top a bit closer to the cart icon in the `Menu below` mode and adjust its height a little bit, so that the `Checkout` and `View cart` buttons are …
=> Fix the mini cart positioning and height for the menu bottom mode on small screens

assets/images.css, sections/images.liquid, templates/apex/index.json, templates/around/index.json, templates/celebrate/index.json, templates/charge/index.json, templates/chic/index.json, templates/coastal/index.json, templates/connect/index.json, templates/construct/index.json, templates/endure/index.json, templates/focus/index.json, templates/move/index.json, templates/radical/index.json, templates/romance/index.json, templates/stellar/index.json, templates/utility/index.json, templates/vogue/index.json, templates/waverunner/index.json
We got an issue when the content of the Hero section was set to not be full width by default after introducing a new option. Yesterday I tried to fix it by changing the default value to true of the new option in schema but apparently, it didn’t work.
So this PR aims to revert this option temporarily
=> Remove the full width content feature in Images section

assets/footer.css, assets/header.css
This PR aims to fix broken text in the Weglot dropdown
Before:
After:
=> Adjust the Weglot dropdown text

assets/sidebar.css, assets/sidebar.js, layout/theme.liquid, snippets/sidebar.liquid
Currently, we have a limited height of collection items in an expanded state in the sidebar on the collection and search pages. Customers complain that it is not clear that user should scroll down the sidebar to see all items. 
Therefore, this PR aims to add some `fade out` effect at the bottom of the block but if it's taller than the parent element
Before:
https://www.loom.com/share/f170e6516551420099d5758dfb0e9526
After:
=> Add automatic `fade out` effect with js for sidebar dropdown if it's taller than parent element

sections/product-page.liquid, templates/construct/product.json, templates/product.json, templates/romance/product.json, templates/vogue/product.json
We've got a request for moving the `Add to cart` button right underneath the price but we can't do that because of at least 2 options (variant, quantity) that the user should choose before adding the product to the cart.
Therefore this PR's purpose is to add a new option "the product description placement: top or bottom". The top option is supposed to be chosen by default which won't change the existing layout.
Before:
After:
=> Add the product description placement option for the product page

sections/hero.liquid, templates/cart.json, templates/page.json
The customer complains that they are using our Translations feature but translation is applied to the browser tab and not the Cart page title:
Therefore, this PR aims to add {{ cart.title }}, {{ page.title }} and {{ page.content }} as a default values to related pages
=> Supporting dynamic titles and descriptions from page context

assets/product-page.css
This PR's purpose is to add padding for product description when it is below the `Add to cart` button on the product page
Before:
After:
=> Add padding for product description

assets/rx.css
The customer complained that the bold style applied to the text section isn't reflected on the site.
This PR's goal is to refactor the font weights of Wysiwyg elements
=> Refactor font weights of Wysiwyg elements

assets/accordion-block.css, assets/account.css, assets/base.css, assets/carousel.css, assets/collections.css, assets/columns.css, assets/contact-form.css, assets/cookie-notice-preferences.css, assets/footer.css, assets/header.css, assets/mosaic.css, assets/numbered-blocks.css, assets/pagination.css, assets/product-card.css, assets/rx.css, assets/sidebar.css, assets/tabs.css, assets/testimonials.css, assets/text-with-image.css, config/settings_schema.json, snippets/date-picker.liquid, snippets/root-styles.liquid, snippets/variables-cart-lines.liquid, snippets/variables-cart-services.liquid, snippets/variables-cart-totals.liquid, snippets/variables-product-gallery.liquid, snippets/variables-product-quantity.liquid, snippets/variables-product-variations.liquid
Some customers would like to get rounded-cornered images and product cards 
So, this PR's purpose is to add a new option that regulates rounded corners of blocks (product cards, block in `Columns` section, image in `Text with image` section, etc.)
Before:
After:
=> Add new border-radius option for styling block and image components

sections/images.liquid, sections/products.liquid, sections/testimonials.liquid, snippets/breadcrumbs.liquid
Before:
After:
I believe we shouldn't fix the color contrast issue, and the customers will be able to handle it by themselves
=> Improve accessibility

assets/base.css, assets/carousel.css, assets/sidebar.css
The scrollbar of the Chameleon-based themes is white, so customers do not notice or realize they need to scroll. 
Therefore, this PR aims to remove styles of scrollbar and let it be styled based on OS.
Before:
After:
=> Remove styles of the scrollbar

layout/checkout.liquid, layout/minimal.liquid, layout/session.liquid, layout/theme.liquid, snippets/page-base-meta.liquid
This pull request introduces an `is_local_env` flag across multiple layout files and updates the `page-base-meta` snippet to conditionally include a `Content-Security-Policy` meta tag based on the environment (it was added on https://github.com/booqable/chameleon-theme/pull/266)
Related https://github.com/booqable/booqable/pull/13577
Now assets are loaded correctly:
=> Adds Content-Security-Policy meta tag for production-only environments

sections/app.liquid
This pull request modifies the logic in the `sections/app.liquid` file to improve how the app section handles previews and missing app data.
* Updated the conditional logic to explicitly check for `section_preview` or a `nil` value for the `app` variable. This ensures that the preview message is displayed when either condition is met.
* Replaced the `unless` block with a more explicit `if`/`else` structure, improving code readability and maintainability.
=> Update app.liquid to show preview content if no app is chosen

assets/js-header-menu.js
This PR refactors the `MegaMenuProcessor` object in `assets/js-header-menu.js` to improve code clarity and consistency by replacing the use of `this.closeMenu()` with `MegaMenuProcessor.closeMenu()` in several methods.
* Replaced `this.closeMenu()` with `MegaMenuProcessor.closeMenu()` in the `if` block inside the `handleMenuToggle` method to ensure consistent usage of the object reference.
* Updated the ternary operation in the `handleMenuToggle` method to use `MegaMenuProcessor.closeMenu()` instead of `this.closeMenu()`.
* Changed the `resizeHandler` function inside `handleMenuResize` to call `MegaMenuProcessor.closeMenu()` instead of `this.closeMenu()`.
* Refactored the condition in an unnamed method to use `MegaMenuProcessor.closeMenu()` for closing the menu, replacing …
=> Refactor MegaMenuProcessor to use explicit method calls

assets/js-cookie-notice-styles-loading.js, assets/js-focal-image.js, assets/js-image-loading.js, assets/js-main.js, assets/js-maps.js, assets/js-utils-core.js
This PR focuses on reducing the size of JS files by simplifying and improving the robustness of observer-related utilities and cleanup methods across various modules, since they have excellent modern browser support and the fallbacks essentially disable functionality rather than provide graceful alternatives. 
The changes remove redundant checks for observer existence and streamline the logic for cleanup and initialization, ensuring consistent behavior.
* Removed redundant `if (!this.observer)` checks in the `cleanup` methods of various components, including `CookieObserver`, `FocalVisibility`, `ImageVisibility`, `MainResize`, `MainVisibility`, and `MapVisibility`. This ensures the cleanup logic is always executed without unnecessary conditional checks
* Removed checks for browser support …
=> Get rid of intersection and resize observers fallbacks

sections/product-page.liquid, templates/construct/product.json, templates/product.json, templates/romance/product.json, templates/vogue/product.json
Since the `variation label` translation is not supported anymore on the theme side (https://github.com/booqable/chameleon-theme/pull/325), so the stuff related to that should be completely removed as well
=> Clean up the `Variation label`

assets/header.css
This PR updates the header logo width. The change ensures that the logo image maintains its aspect ratio by setting its width to auto, which helps prevent any distortions
=> Fix header logo stretches
