booqable/chameleon-theme

assets/header.js
Fixed error that exists when opening the search
=> Search error fix

assets/account.css, assets/base.css, assets/carousel.css, assets/cart.css, assets/header.css, assets/main.js, assets/rx.css, sections/cart.liquid, snippets/date-picker.liquid, snippets/page-metadata.liquid, snippets/variables-cart-lines.liquid, snippets/variables-cart-services.liquid, snippets/variables-cart-totals.liquid, snippets/variables-mini-cart.liquid, snippets/variables-product-gallery.liquid, snippets/variables-product-quantity.liquid, snippets/variables-product-variations.liquid, templates/cart.json
1. Added cart page
2. Added some CSS variables
3. Fixed href attribute of favicon URL
4. Fixed size of the badge of the cart icon
5. Increased delay time of Settimeout function
=> Added cart page and some minor fixes

assets/base.css, assets/columns.css, assets/footer.css, assets/logos.css, assets/map.css, assets/mosaic.css, assets/numbered-blocks.css, assets/pagination.css, assets/product-page.css, assets/tabs.css, config/settings_schema.json, snippets/date-picker.liquid, snippets/root-styles.liquid, snippets/variables-cart-services.liquid
Since the development of a new Impact theme has started, there were noticed some issues that must be fixed
Changelog:
1. Date picker CSS variables brought to common style
2. Corrected default (fallback) color of —color-secondary variable
3. Added line-height to bq-cart-services component
4. Changed name from Tough to Chameleon in settings_schema.json
5. Removed unused CSS variables
=> Styles improvements

assets/base.css, assets/hero.css, assets/images.css, config/settings_schema.json, snippets/root-styles.liquid
The Product owner has decided to not allow the customers to the animation settings
=> Removed animation option from General settings

assets/header.css, assets/mega-menu.css, assets/top-bar.css, layout/theme.liquid, sections/header.liquid
This PR adjusts the layout to implement "Add to cart button behavior" in the theme
=> Add to cart button behavior layout

sections/accordion.liquid, sections/collection-page.liquid, sections/footer.liquid, sections/header.liquid, sections/locations.liquid, sections/logos.liquid, sections/search.liquid
The purpose of the PR is to prevent a browser from crashing when the number of blocks is over 20 and some typos corrections as well
=> Limitation of the number of blocks

assets/top-bar.css
Small improvement of indents of text on `Top bar` section
=> Indents correction

sections/hero.liquid, sections/images.liquid
Both sections should be available for all pages / templates for more flexibility.
=> "Images" and "Hero" sections available on all templates

sections/locations.liquid
We temporarily removed the locations section for initial release. This PR preserves the original implementation so we can improve on it.
=> Add and improve Locations section

sections/login-form.liquid
=> Add info alert on login page

assets/hero.css, layout/theme.liquid, sections/header.liquid
There were noticed bugs in the `Hero` and the `Images` sections which should be fixed.
1. The Date picker styles where it's at the bottom of the section were carelessly removed in the `Hero` section, so they should be put back.
2. Recently the `Images` section has been available on all pages but the js file of the YouTube video that is related to this section should be available for all pages as well.
3. Also, refactored the script in `Header`
=> Fixed bugs of the `Hero` and the `Images` sections

sections/footer.liquid, sections/images.liquid, sections/products.liquid, sections/testimonials.liquid, snippets/breadcrumbs.liquid
The purpose of the PR is to improve existing web-accessibility
=> Web accessibility improvements

assets/spacer.css, sections/spacer.liquid
A new section called `Spacer`. It will be a simple section adding a vertical white space between other sections. It should have one configuration variable `Size` with the following options:
1. Small (32px)
2. Medium (64px)
3. Large (128px)
=> Implement `Spacer` section

assets/header.js, assets/main.js, assets/rx.css, sections/header.liquid, sections/images.liquid
The purpose of the PR is to prevent a few JS errors:
1. If the menu does not exist;
2. If the Date picker position is not at the bottom of the section. 
Also fixed semantics for text tags
=> Preventing js errors, fixed semantics

sections/call-to-action.liquid
Previously wrong variables were used so buttons always led to home page and not the set url.
=> Use correct variables for CTA section links

layout/minimal.liquid
=> Added minimal layout

layout/checkout.liquid
Without it the new checkout does not work.
=> Add checkout layout

sections/activate-account.liquid
This PR brings the Chameleon theme in sync with the Cart 2.0 post release changes in the core repo
- Removed unspecified cart redirects as it's not supported anymore
=> Improvement: Cart 2.0 post release changes

config/settings_schema.json, layout/theme.liquid, sections/cookie-notice-preferences.liquid, sections/footer.liquid, templates/privacy-policy.json
This PR implements the Cookie Notice feature inside the Chameleon theme.
Linear ticket: [SHOP-978](https://linear.app/booqable/issue/SHOP-978/add-cookie-notice-to-chamelon-theme)
=> Add cookie notice to Chamelon theme

assets/footer.css, assets/header.css, sections/footer.liquid, sections/header.liquid
This PR addresses issues mentioned by @srgzlb in #187.
=> Tweak theme to use BEM for app components and valid HTML

snippets/variables-mini-cart.liquid
This PR goes in combo with https://github.com/booqable/booqable/pull/10514
=> Add missing cart color variables

snippets/variables-mini-cart.liquid
Just add missed `--minicart-accent-outline` variable to minicart
=> Add missed `minicart-accent-outline` variable to minicart

layout/checkout.liquid
This reverts commit 36ef3099cdef60262fcf7477e192a9b720aff371.
=> Revert "Use checkout specific header content"

sections/activate-account.liquid, sections/login-form.liquid, sections/register-form.liquid
https://linear.app/booqable/issue/SHOP-1188/checkout-next-customer-accounts-are-not-translated
=> Update login button label in activate-account, login-form, and register-form

assets/call-to-action.css, assets/hero.css, assets/numbered-blocks.css, sections/call-to-action.liquid, sections/cookie-notice-preferences.liquid, sections/numbered-blocks.liquid, snippets/script-date-picker-background.liquid, templates/celebrate/index.json, templates/construct/index.json, templates/endure/index.json, templates/utility/index.json, templates/vogue/index.json
Improving some sections for better visual displaying in the preview app
=> Improving sections for the preview app

sections/footer.liquid, sections/header.liquid, sections/top-bar.liquid
The following changes are required to omit the layout sections from injecting the "Add section" HTML snippet
=> Mark layout sections

assets/base.css, snippets/variables-product-gallery.liquid
Similar [fix as in the Impact theme](https://github.com/booqable/impact-theme/pull/96) for Font awesome icon colors to match the current color of section and apply consistent border-radius styles for the date picker modal window
=> Fix CSS styling for the Date picker

assets/base.css, assets/hero.css, assets/product-page.css, sections/hero-search.liquid, sections/hero.liquid, templates/cart.json, templates/page.json
This PR's purpose is to fix blank space between a single section on page and the footer if browsing on big screens
[Initial PR](https://github.com/booqable/impact-theme/pull/101)
=> Fix blank space at the end of a page if there is only 1 section on the page

sections/collection-page.liquid, sections/search.liquid
This PR's goal is to fix the sidebar issue when it is not showing if the menu is not chosen in the last block on the Collection/Search pages
=> Fix sidebar menu issue when it is not showing

assets/cookie-notice-preferences.css, sections/cookie-notice-preferences.liquid, templates/privacy-policy.json
Currently, the cookie notice colors adjust in 2 different places in the global settings and the cookie notice section but it is supposed to be in 1 place.
So this PR aims to update the cookie notice color adjustments and add settings a bit to its section.
=> Cookie notice updates

assets/404.css, assets/base.css, templates/page.json
=> Fix blank space between the last section and the footer on big screens

assets/404.css, assets/base.css, sections/cookie-notice-preferences.liquid
[Here is initial issue](https://github.com/booqable/impact-theme/pull/106)
=> Fix the border-radius of locations in a new date picker

assets/images.css, sections/images.liquid, templates/apex/index.json, templates/around/index.json, templates/celebrate/index.json, templates/charge/index.json, templates/chic/index.json, templates/coastal/index.json, templates/connect/index.json, templates/construct/index.json, templates/endure/index.json, templates/focus/index.json, templates/move/index.json, templates/radical/index.json, templates/romance/index.json, templates/stellar/index.json, templates/utility/index.json, templates/vogue/index.json, templates/waverunner/index.json
Initial issue https://github.com/booqable/horton-theme/pull/67
=> Add `max-width` option for the Hero section content

sections/images.liquid
Initial issue https://github.com/booqable/horton-theme/pull/70
=> Update the default value to true for full-width content in the Hero section

assets/images.css, sections/images.liquid, templates/apex/index.json, templates/around/index.json, templates/celebrate/index.json, templates/charge/index.json, templates/chic/index.json, templates/coastal/index.json, templates/connect/index.json, templates/construct/index.json, templates/endure/index.json, templates/focus/index.json, templates/move/index.json, templates/radical/index.json, templates/romance/index.json, templates/stellar/index.json, templates/utility/index.json, templates/vogue/index.json, templates/waverunner/index.json
Initial issue https://github.com/booqable/horton-theme/pull/73
=> Add limit content by width option in Images section

assets/product-card.css, config/settings_data.json, config/settings_schema.json, sections/collection-page.liquid, sections/products.liquid, sections/search.liquid, snippets/product-card.liquid, templates/apex/index.json, templates/around/index.json, templates/charge/index.json, templates/chic/index.json, templates/collection.json, templates/construct/index.json, templates/construct/product.json, templates/endure/index.json, templates/focus/index.json, templates/product.json, templates/radical/index.json, templates/romance/index.json, templates/romance/product.json, templates/search.json, templates/stellar/index.json, templates/utility/index.json, templates/vogue/index.json, templates/vogue/product.json, templates/waverunner/index.json
This PR aims to move all settings related to product cards from sections to the theme's Global settings as we made in other themes. Besides that, some new options are going to be added to standardize all product card settings across all themes.
=> Move product card settings to General settings of theme

assets/accordion-block.css, assets/account.css, assets/base.css, assets/carousel.css, assets/collections.css, assets/columns.css, assets/header.css, assets/header.js, assets/images.css, assets/map.css, assets/mega-menu.css, assets/pagination.css, assets/product-page.css, assets/sidebar.css, assets/tabs.css, layout/session.liquid, layout/theme.liquid, snippets/critical-css.liquid
For better page performance, we should implement critical CSS extraction for above-the-fold content and load it earlier ASAP
Also, there is no need to use the `header fixed` js function because this functionality was implemented with CSS
=> Add critical above-the-fold css styles

config/settings_schema.json, snippets/socials.liquid
Currently, pages don't follow basic search engine optimization guidelines to their fullest extent. Therefore, this PR aims to improve page SEO
Before:
After:
=> SEO improvements

assets/rx.css
Initial [issue](https://github.com/booqable/impact-theme/pull/120)
=> Add margin-bottom reset for the last heading elements in WYSIWYG

snippets/scripts-loading.liquid
This pull request refactors and enhances the script-loading logic in the `snippets/scripts-loading.liquid` file. The changes focus on improving script loading efficiency, ensuring sequential loading of critical scripts, and adding error handling for better reliability.
* **Sequential loading for critical scripts**: Updated the logic to load critical scripts in sequence to maintain their defined order. This ensures that dependencies between critical scripts are respected.
* **Optimized non-critical script loading**: Adjusted the loading of non-critical scripts to use `requestIdleCallback` with a reduced timeout or a fallback to `setTimeout`, ensuring they load after critical scripts without blocking the main thread.
* **Error handling for script loading failures**: Introduced an error …
=> Optimize script loading strategy for better performance

assets/js-utils-core.js, assets/js-utils.js, snippets/scripts-base-layout.liquid
This pull request introduces a modular JavaScript utility library (`js-utils-core.js` and `js-utils.js`) to enhance code reusability, maintainability, and performance. It also updates the script loading order in the base layout to prioritize critical utilities. Below are the key changes grouped by theme:
* Added a new `js-utils-core.js` file with essential utility functions for type checking, event management, viewport detection, performance optimization, and modern browser features. This serves as the foundational utility library.
* Introduced `js-utils.js` as an optional extension to the core utilities, adding features like sibling element traversal, touch device detection, and custom event triggering. It depends on `js-utils-core.js` being loaded first.
* Updated the …
=> Add utility functions and update script loading for the base layout

assets/js-text-with-image.js, snippets/scripts-loading.liquid
This pull request refactors and optimizes the `handleTextWithImageSpacer` function to improve performance and maintainability. The changes include caching elements and functions, leveraging the `Utils` library for DOM operations, and introducing batch processing and frame sequencing for efficient updates.
* Replaced direct DOM access with cached element retrieval functions (`getElements`) and utility methods like `$.getSibling` to minimize DOM queries.
* Introduced `$.batchDOM` and `$.frameSequence` from the `Utils` library to optimize DOM updates and ensure smoother transitions.
* Refactored palette detection logic into reusable helper functions (`findPalette`, `hasPalette`, `hasSpacerClass`) to reduce code duplication and improve readability.
* Consolidated logic for finding and …
=> Refactor text-with-image spacer logic for improved performance

assets/js-touch-device-notch.js, snippets/scripts-loading.liquid
This pull request introduces performance optimizations and better resource management for the `handleTouchDevice` functionality, along with integration of a cleanup mechanism in the global script lifecycle. Key changes include throttling for resize events, leveraging utility functions to reduce layout thrashing, and adding a destroy method for proper cleanup.
* [`assets/js-touch-device-notch.js`](diffhunk://#diff-a087caa8c59aead68bdd995f39260eac1411ee4cb39b34479b42f48e55732d80R31-R51): Added throttling for resize events and optimized the `detectNotch` function by using the `frameSequence` utility to separate read and write phases, reducing layout thrashing. [[1]](diffhunk://#diff-a087caa8c59aead68bdd995f39260eac1411ee4cb39b34479b42f48e55732d80R31-R51) …
=> Enhance touch device handling script for better performance

assets/js-image-loading.js, assets/mosaic.css, sections/images.liquid, snippets/critical-css.liquid, snippets/image.liquid, snippets/scripts-loading.liquid
This pull request introduces significant updates to the image loading functionality, focusing on improving performance, optimizing lazy loading, and enhancing user experience. Key changes include refactoring the JavaScript image loading logic, updating CSS for better rendering and animation, and modifying Liquid templates to support adaptive loading strategies.
* Refactored `handleImageLoading` in `assets/js-image-loading.js` to optimize lazy loading using `IntersectionObserver`, prioritize visible images, and adapt loading strategies based on device capabilities (e.g., slow connections, low memory). Added support for modern features like `fetchPriority` and `importance` attributes. [[1]](diffhunk://#diff-fccc3db0fc8e550822076f1976a3f663792f178be89cf00f6c90fe1d5be15ab5R1-R10) …
=> Enhance image loading performance

assets/js-focal-image.js
After discussions in previous PRs of improving performance, it turned out that the code was a bit difficult to read and maintain, so it was decided to make it modular. 
Therefore, this PR just refactors the `assets/js-focal-image.js` file to modularize the focal image handling logic, improve readability, and enhance maintainability. The changes include splitting functionality into distinct objects, introducing a cleanup mechanism, and ensuring idempotent initialization.
* The focal image handling logic is now divided into modular objects: `FocalConfig`, `FocalDOM`, `FocalCalculator`, `FocalProcessor`, and `FocalVisibility`. Each object encapsulates related responsibilities, improving code organization and readability. [[1]](diffhunk://#diff-ab994ad365f94775b6edfd3873aa911131df47694ce907a3d …
=> Make Focal Image Component modular for consistency

assets/js-cookie-notice-styles-loading.js, assets/js-utils-core.js
This pull request refactors and modularizes the cookie consent styles loader, improving maintainability and performance. The functionality and UI haven't been changed. 
The PR introduces a new component-based architecture with a clear separation of concerns and adds a utility function for creating `MutationObserver` instances.
* Refactored `assets/js-cookie-notice-styles-loading.js` into a modular architecture using components (`CookieConfig`, `CookieDOM`, `CookieStyler`, `CookieObserver`, `CookieInterval`, and `CookieHandler`) to improve readability and maintainability.
* Replaced direct DOM manipulations and global variables with encapsulated methods and caching for better performance and reduced side effects.
* Enhanced fallback mechanisms with a configurable interval and maximum …
=> Make cookie notice styles loader modular

assets/js-text-with-image.js
This PR refactors the `Text With Image Spacer` function in `assets/js-text-with-image.js` to improve code modularity, performance, and maintainability. The changes include restructuring the code into distinct modules, introducing caching mechanisms, and optimizing DOM operations for better performance.
* The code has been restructured into distinct modules: `TextImageConfig`, `TextImageDOM`, `TextImageDetector`, `TextImageRenderer`, and `TextImageProcessor`, each handling specific responsibilities. This modular approach enhances readability and maintainability.
* Introduced caching for spacer and previous section elements using `Map` objects in `TextImageDOM` to reduce redundant DOM queries.
* Optimized DOM updates by using a single `$.frameSequence` for batch processing of read and write …
=> Refactor `text-with-image.js` to modular

assets/base.css, assets/js-touch-device-notch.js
This PR aims to refactor the touch device with notch component to modular improving maintainability and readability, and CSS adjustments for better responsiveness. The changes include a complete refactor of the `handleTouchDevice` functionality, enhancements to CSS for landscape orientation on touch devices, and improved initialization and cleanup processes.
* Refactored the `handleTouchDevice` function into a modular architecture with three key components: `TouchConfig` (configuration and constants), `TouchDOM` (DOM-related state and caching), and `TouchRenderer` (logic for detecting and updating notch-related data). This improves code readability and separation of concerns. [[1]](diffhunk://#diff-a087caa8c59aead68bdd995f39260eac1411ee4cb39b34479b42f48e55732d80L11-R20) …
=> Refactor touch device notch component to modular and enhance styling for better user experience

assets/js-focal-image.js, assets/js-main.js, assets/js-maps.js, assets/js-text-with-image.js, assets/js-touch-device-notch.js, assets/js-utils-core.js
This PR refactors cleanup logic to streamline and centralize the cleanup process using a new utility method. The changes improve code maintainability by replacing repetitive cleanup logic with a standardized approach.
* [`assets/js-utils-core.js`](diffhunk://#diff-4cb82b9137a8cea1a033f207a64168a9501dfdcdebe3d8e6c497edc3bbac17b1R69-R91): Added `Utils.cleanup` method to handle cleanup functions in a consistent and reusable way, integrating with the global theme cleanup system.
* [`assets/js-focal-image.js`](diffhunk://#diff-ab994ad365f94775b6edfd3873aa911131df47694ce907a3d738e666361ca223L150-R150): Replaced custom cleanup logic for `cleanupFocalImages` with the `Utils.cleanup` utility.
* [`assets/js-main.js`](diffhunk://#diff-4d65aa18241cfe7da848868aeeec3633e3ad03fde89bb707b41904e563cd2920L2 …
=> Refactor cleanup functions to use centralized cleanup utility

sections/footer.liquid, sections/images.liquid
Same as https://github.com/booqable/chameleon-theme/pull/299 but we didn't port it to `main`
=> Fixes liquid errors

assets/account.css, assets/base.css, assets/header.css, assets/js-top-bar.js, snippets/critical-css.liquid
This PR focuses on simplifying the handling of CSS variables and JavaScript logic related to sticky headers, top bars, and scrolling behavior. The changes aim to remove unnecessary complexity, improve maintainability, and ensure consistent behavior across the UI.
* [`assets/account.css`](diffhunk://#diff-d1083fc84d1520ec33381e6fbd0bc2a10f2ded32aeb0c8f88ca78d67dc77db5eL201-R204): Adjusted the `top` and `height` calculations for the `.account__agreement-modal` to remove the redundant `--header-transform` variable. Added new styles for `.scrolled-down` to handle scrolling behavior for the modal. [[1]](diffhunk://#diff-d1083fc84d1520ec33381e6fbd0bc2a10f2ded32aeb0c8f88ca78d67dc77db5eL201-R204) [[2]](diffhunk://#diff-d1083fc84d1520ec33381e6fbd0bc2a10f2ded32aeb0c8f88ca78d67dc77db5eR213-R217)
* …
=> Streamline functionality by replacing redundant JavaScript with CSS solutions

assets/js-carousel.js, assets/js-image-loading.js
This PR introduces enhancements to the carousel and image-loading components, focusing on performance optimization, improved DOM handling, and better image preloading. Key changes include adding a new `imageHidden` selector for preloading hidden images, replacing `getBoundingClientRect` with a new utility method for dimension calculations, and batching DOM updates to reduce layout thrashing.
* Added a new `imageHidden` selector to `CarouselConfig` for identifying hidden images to preload. (`assets/js-carousel.js`, [assets/js-carousel.jsL22-R23](diffhunk://#diff-8ddfbf1aa88c80079afece91bb04ac319b170fc89bbf156093bf9284fa6af222L22-R23))
* Introduced `preloadCarouselImages` method in `CarouselController` to preload hidden images using the new selector and `$.imageLoader`. …
=> The images are not loaded in the carousel

assets/images.css, assets/js-carousel.js, assets/js-video-loading.js, sections/images.liquid, snippets/scripts-loading.liquid
This PR's purpose is to create a comprehensive YouTube and Vimeo video management system for carousel items, preventing memory leaks and page crashes.
This system transforms a basic carousel into a sophisticated video player that manages multiple embedded videos intelligently while maintaining smooth user experience and optimal performance.
Smart video loading and playback management for carousels that contain embedded videos, with intelligent memory management and state persistence.
Key features
1. Smart 2-video window loading
- Only loads 2 videos at once: current and next slides
- Uses circular logic for proper carousel wrapping (last ↔ first slide)
- Destroys off-screen videos to save memory
2. Video state persistence
- Saves video timestamps when slides change
- Restores playback …
=> Enhance video handling
